### ISSUE TITLE
SD Stake Pool Setup

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Website#24]
## Goal
Have a SecretDecks stake pool running!

## Specifications / To Do's
- [x] generate stake keys off hardware wallet (via CLI)
- [x] find ticker name: TAROT
- [x] #25
- [x] acquire ADA for pledge
- [ ] setup info / content on website 
- [ ] create sub domain
- [ ] config DNS & upload SPO files 

- [x] Pledge of 2,5k ADA has been made to pool address 

addr1qy2gzna7727g5d5732pzg5jk6pnf08048ufhw2ttds5k0m2e3lvek67fqhxl99dwynxas6ztq76f0vqxy0ajnjvkmyas06cnnl

**Comment by DanM3rcurius** [comment]
- [ ] keys have been generated on Friday (12th Nov). 

- [ ] Pledge of 2,5k ADA has been made to pool address 

addr1qy2gzna7727g5d5732pzg5jk6pnf08048ufhw2ttds5k0m2e3lvek67fqhxl99dwynxas6ztq76f0vqxy0ajnjvkmyas06cnnl

- [ ] create sub domain
- [ ] write text blurb
- [ ] config DNS & upload SPO files
