### ISSUE TITLE
Main - Artist Story 

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Website#5]
# Story
As an artist / content creator I'm interested in creating digital collectible art related to Tarot;
I see an image (of a card) on the main page that asks: "Are you an artist?";
I immediately feel this is the card I want to select

-> Links to Artist collab. section with discord invite link

# Goals
This user story will onboard 5 artists within 1 month that start contributing to SecretDecks SUMMONINGS (either offering an existing deck or coop on a new)

# Specifications

- card artwork (Temperance) 
- Change card title
- artist blurb (behind card link)
- discord link (behind card link)

# Task

- [x] create Miro wireframe for page section @DanM3rcurius @wlstylr 
- [x] #20
- [x] #13
- [x] #19
- [x] create infinite discord link @DanM3rcurius 
- [x] design Figma Prototype @sarafanciulli 
- [x] setup Discord Artist onboarding channel @DanM3rcurius 
- [ ] create artist form @wlstylr 
- [ ] test!

# QualityAssurance

## Test Cases
* Open www.secretdecks.com
* select <Card with Artist artwork>
* display of <Artist blurb> and discord link
* Discord link select leads to Discord Artist channel

## Acceptance Test
* See new artist in Discord
* hear about new deck collabs in SD townhall

**Comment by DanM3rcurius** [comment]
## Main - Artist Story: notes from SprintPlanning no.1

- [ ] figure out copy for two "calls to action" (what does it mean to be an artist?) for a) typeform b) Discord link

- do we need to mention NFT? - Heather
- no. lets use term digital collectible - Dan, Tyler
- *"As an artist / content creator I'm interested in creating digital collectible art related to Tarot"* - proposal for rewriting first story sentence - Dan 
- if we keep 3 cards, then blurb above 3 cards explaining  in general all 3 cards, why is the choice they make 
- Blurb should contain: "looking to create a tarot metaverse experience" - Dan
- little information before clicking card is better for UX - Sara
- current blurb: last sentence "conjured disco & cardano"
  - conjured in a DisCo and built on Cardano
  - What tha Thoth is Tarot: info overload; needs another position - Tyler, Heather
  - more information! - Sara
  - "Just another NFT drop": different position - Tyler
  - possibility to just use text (blurb headings) instead of cards - Tyler, Dan
  - Founders Drop setup in Discord: structure, drop date, incentives - Tyler
  - modify wait smith deck cards to have them on page, extract or relief  - Sara
  - user tests, do them often and with anyone available - Tyler, Sara
 - first Planning Poker! we add together or average estimations? - we discuss!

**Comment by wlstylr** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/SecretDecks-Relaunch--Founders-Drop-615413e56a2e7e0012d7f67b/issues/SecretDecks/Website/5?planning-poker) with ZenHub @evolayak @sarafanciulli @DanM3rcurius

**Comment by DanM3rcurius** [comment]
![XIV-temperance-rework-3](https://user-images.githubusercontent.com/80257662/139288348-2502cd6c-73ca-4576-ac2b-93d474bb13a2.png)

current card mockup

**Comment by wlstylr** [comment]
Looks cool; Do you think Temperance is readable enough?  I think I like it as is.  Going to see how it looks on the website

**Comment by DanM3rcurius** [comment]
Do we want it to be more readable?
Should I experiment with more variations?

**Comment by DanM3rcurius** [comment]
Artist link to onboarding channel
https://discord.gg/gQR54Bs3uj
