### ISSUE TITLE
Main - NFT Collector Story

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Website#6]
# Story 
As an NFT collector I'm always looking for the newest, hottest drops and interesting communities to "invest in" early on if possible;
I see an image of a card on the main page that reads: "Are you a NFT collector?";
I immediately know this is the card for me to select, in order to find out about the first and hopefully a little info on future drops

-> Links to DROPS (teaser) and call to action in the teaser section for FoundersDrop
-> Alternative: instead of teaser page, link to dedicated discord channel

# Goals
This user story will onboard 10 NFT collectors within 1 month that buy the Founders Elements.

# Specifications

- card artwork (XVIII - The Moon) 
- Change card title to "?"
- NFT collector blurb (behind card link)
- discord link (behind card link)

# Task
- [x] create Miro wireframe for page section @DanM3rcurius @wlstylr 
- [x] #16 
- [x] find title for card
- [x] #22
- [x] create infinite discord link @DanM3rcurius 
- [x] create Link to FoundersDrop in GitBook
- [x] design Figma Prototype @sarafanciulli 
- [x] setup Discord Collector onboarding (Founders Drop) channel open @DanM3rcurius 
- [ ] test!

# Specifications
landing page
card artwork (enticing NFT collector)

[Drops teaser page/section] **nice to have**
Link to dedicated discord channel
call to action to founders drop 

# QualityAssurance

## Test Cases
* Open www.secretdecks.com
* select <Card with Collector artwork>
* display of <collector blurb> and discord link
* Discord link select leads to Discord Artist channel

* Alternative: Drop teaser page after selecting card

## Acceptance Test
* See new artist in Discord
* hear about new deck collabs in SD townhall

**Comment by DanM3rcurius** [comment]
## Notes from SprintPlanning no1

- initially going to discord and structure info there - Tyler
- short drop about founders drop - Tyler
- what card to use? The Moon? Emperor? Hierophant? - all
- Grounded? material focused - Heather
- Moon it is; "moonboys" speculative aspect but also the emotional / intuitive choice to commit to a project/NFT community
- Title for card?
 - Community? - Dan
 - Patronage?

**Comment by DanM3rcurius** [comment]
Discord Founders Drop announcement channel: https://discord.gg/vyA89FyCfn

**Comment by DanM3rcurius** [comment]
GitBook founders drop link: https://secretdecks.gitbook.io/arcana/introduction/the-founders-drop

**Comment by DanM3rcurius** [comment]
TITLE: Collector

**Comment by DanM3rcurius** [comment]
new version in #16
