### ISSUE TITLE
Main - Tarot Story

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Website#7]
# Story
As a Tarot enthusiast I want to engage with the Tarot on new levels;
I see a well known card on the main page "XXI - The World";
I immediately know this is the card for me to select in order to find out more about the Tarot metaverse

-> Links to GitBook "The metaverse"

# Goals
This user story will onboard 10 tarot heads within 1 month that start contributing to SecretDecks GitBook (lore or publications) 

# Specifications

- card artwork (XXI- The World) 
- Change card title to "The Metaverse")
- tarot blurb (behind card link)
- discord link (behind card link)

# Task

- [x] create Miro wireframe for page section @DanM3rcurius @wlstylr 
- [x] #15 
- [x] #21
- [x] create infinite discord link @DanM3rcurius 
- [x] create Link to Metaverse in GitBook
- [x] design Figma Prototype @sarafanciulli 
- [x] setup Discord Tarot onboarding channel open @DanM3rcurius 
- [x] test!

# QualityAssurance

## Test Cases
* Open www.secretdecks.com
* select <XXI>
* display of <Tarot blurb> and discord link
* Discord link select leads to Discord Tarot channel

## Acceptance Test
* See new tarot interested members & tarot discussions in Discord
* hear new members talk about their GitBook content created

**Comment by DanM3rcurius** [comment]
## Notes from SprintPlanning no.1

- have direct link to gitbook behind World? - Sara
- link to Discord in GitBook metaverse chapter in the beginning of Gitbook page - Dan
- only link to GitBook?
- cut number of clicks - Heather
- flip card, blurb explaining, links on back as well - Tyler

**Comment by wlstylr** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/SecretDecks-Relaunch--Founders-Drop-615413e56a2e7e0012d7f67b/issues/SecretDecks/Website/7?planning-poker) with ZenHub @DanM3rcurius @evolayak @sarafanciulli

**Comment by DanM3rcurius** [comment]
@wlstylr see my reference above for terminology of Discord onboarding channels (reception & incubate)

**Comment by DanM3rcurius** [comment]
![XXI-the_world-rework-3](https://user-images.githubusercontent.com/80257662/139287430-28dfc078-7a6c-473f-923d-fe96ec4f1941.png)

new card mockup

**Comment by DanM3rcurius** [comment]
Tarot onboarding channel:
https://discord.gg/q9d9AeCfaC

**Comment by DanM3rcurius** [comment]
new version in #15
