### ISSUE TITLE
Main - Gov Story

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Website#8]
# Story

As someone who has knowledge about governance and self organising communities, I'm interested in shaping the governance tools of tomorrow;
Since I'm naturally curious I see a navigation point that says "Governance in the DisCo";
I have a strong sense that this is what I need to select to find out more about what interests me

-> Links to  gov main section (also GitBook "how we do stuff")

# Goals
This user story will onboard 5 cooperative members within 1 month that start contributing actively to the governance process design (substantial edits on Miro board and/or GitHub pull requests)

# Specifications
* DisCo blurb (about us section)
* infinite discord link to welcome thread https://discord.gg/Ww85r7yJMk
* GitBook link to gov intro https://secretdecks.gitbook.io/arcana/introduction/who-and-what-is-secretdecks

# Task
- [x] create Miro wireframe for landing page @DanM3rcurius @wlstylr 
- [x] add navigation link "Governance in the DisCo" @sarafanciulli 
- [x] write gov entry page in GitBook @DanM3rcurius 
- [x] write DisCo blurb @DanM3rcurius 
- [x] create infinite discord link to welcome channel @DanM3rcurius 
- [x] design Figma Prototype @sarafanciulli 

# QualityAssurance

## Test Cases
* Open www.secretdecks.com
* select Governance in the DisCo
* display about us section
* Discord link select leads to Welcome channel

## Acceptance Test
* See new artist in Discord
* hear about new deck collabs in SD townhall

**Comment by DanM3rcurius** [comment]
## Notes from SprintPlanning no.1
- short DisCo (whats diff to corporation) blurb with link to GitBook and Discord on main; small content bar above footer - Tyler
- Governance (to Consensus building and voting)
- having navigational point and link off page is confusing for UX - Sara, Tyler

**Comment by wlstylr** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/SecretDecks-Relaunch--Founders-Drop-615413e56a2e7e0012d7f67b/issues/SecretDecks/Website/8?planning-poker) with ZenHub @DanM3rcurius @evolayak @sarafanciulli

**Comment by DanM3rcurius** [comment]
![Screenshot 2021-10-20 at 22 44 27](https://user-images.githubusercontent.com/80257662/138169432-a2e58031-b25f-425b-abc7-895486050e04.png)

@wlstylr thoughts?

**Comment by wlstylr** [comment]
Yes, this looks and reads like the right content for governance.  It will sit below the choose a card section, correct?

**Comment by DanM3rcurius** [comment]
> It will sit below the choose a card section, correct?
@wlstylr yes that's what I was thinking but would love @sarafanciulli s input as well!

**Comment by DanM3rcurius** [comment]
BTW the colours are intentionally over emphasised so the elements have better visibility;
placement is not final and can be tweaked if needed @sarafanciulli

**Comment by DanM3rcurius** [comment]
Added the following GitBook link in "Specifications" above. https://secretdecks.gitbook.io/arcana/introduction/who-and-what-is-secretdecks

**Comment by DanM3rcurius** [comment]
Created infinite discord invite link to welcome channel
https://discord.gg/Ww85r7yJMk
(added to "specifications" above as well)
